name: 'Post'
description: 'Posts PR notifications to slack'
inputs:
  slack-bot-token:
    description: 'API token to post messages to slack'
    required: true
  channel-id:
    description: 'Channel that manages PR notifications'
    required: true
  action:
    description: 'Slack action to take'
    required: true
  message:
    description: 'Slack message template'
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'dist/index.js'
